// src/views/game/FFXIV.vue
<template>
  <div class="fill-height">
    <v-tabs v-model="tab" color="info" @change="handleTabChange">
      <v-tab href="#tab-0">关于</v-tab>
      <v-tab href="#tab-1">陆行鸟</v-tab>
      <v-tab href="#tab-2">莫古力</v-tab>
      <v-tab href="#tab-3">猫小胖</v-tab>
    </v-tabs>
    <v-tabs-items v-model="tab" class="fill-height">
      <v-overlay absolute :opacity="1" color="white" :value="loading">
        <v-progress-circular indeterminate color="primary"></v-progress-circular>
      </v-overlay>

      <v-tab-item key="tab-0" value="tab-0">
        <v-container class="pa-10">
          <v-alert type="success">{{ formatedDate }}</v-alert>
          <v-card class="mx-auto mt-10 pa-2">
            <v-list-item two-line v-for="(sec, index) of info" :key="`info-${index}`">
              <v-list-item-content>
                <v-list-item-title>{{ sec.title }}</v-list-item-title>
                <v-list-item-subtitle>
                  <template v-if="sec.link">
                    <a :href="sec.text" target="_blank">{{ sec.text }}</a>
                  </template>
                  <template v-else>{{ sec.text }}</template>
                </v-list-item-subtitle>
              </v-list-item-content>
            </v-list-item>
          </v-card>
        </v-container>
      </v-tab-item>

      <v-tab-item
        v-for="(area, index) of data"
        :key="`tab-${index + 1}`"
        :value="`tab-${index + 1}`"
      >
        <div>
          <span class="table-title">5.X 狩猎车列表</span>
          <v-data-table
            :headers="headers"
            :items="area.shadowbringers"
            hide-default-footer
            dense
            disable-filtering
            disable-pagination
            disable-sort
          ></v-data-table>
        </div>
        <v-divider></v-divider>
        <div>
          <span class="table-title">4.X 狩猎车列表</span>
          <v-data-table
            :headers="headers"
            :items="area.stormblood"
            hide-default-footer
            dense
            disable-filtering
            disable-pagination
            disable-sort
          ></v-data-table>
        </div>
      </v-tab-item>
    </v-tabs-items>
  </div>
</template>

<script>
import storage from '@/utils/storage';

export default {
  name: 'FFXIV',
  data() {
    return {
      loading: true,
      data: [],
      lastUpdate: new Date(0),
      tab: storage.getLS('dsr-tools_ffxiv-tab') || 'tab-0',
      headers: [
        { text: '服务器', value: 'server', align: 'center' },
        { text: '早车', value: 'timeTable[0]', align: 'center' },
        { text: '午车', value: 'timeTable[1]', align: 'center' },
        { text: '晚车', value: 'timeTable[2]', align: 'center' },
        { text: '灵车', value: 'timeTable[3]', align: 'center' },
        { text: '始发地', value: 'origin', align: 'center' },
        { text: '路线', value: 'route', align: 'center' },
      ],
      info: [
        {
          title: '数据不刷新问题',
          text: '数据更新后 CDN 缓存需要约 10-15 分钟全球刷新, 若出现问题则最高需要 12 小时',
          link: false,
        },
        {
          title: '错误反馈',
          text: '请使用右下角按钮直接进行客服提问反馈, 或至 NGA 原帖回帖反馈',
          link: false,
        },
        {
          title: '感谢访问',
          text: '如果觉得本站对您有所帮助还请多多分享, 用户的使用是我更新的最大动力',
          link: false,
        },
        { title: 'NGA 原帖', text: 'https://nga.178.com/read.php?tid=20339590', link: true },
      ],
    };
  },
  computed: {
    formatedDate() {
      let date = this.lastUpdate;
      let year = date.getFullYear();
      let month = `${date.getMonth() + 1}`.padStart(2, '0');
      let day = `${date.getDate()}`.padStart(2, '0');
      let h = `${date.getHours()}`.padStart(2, '0');
      let m = `${date.getMinutes()}`.padStart(2, '0');
      let s = `${date.getSeconds()}`.padStart(2, '0');
      return `最后更新于 ${year}-${month}-${day} ${h}:${m}:${s}`;
    },
  },
  methods: {
    async fetchData() {
      const response = await this.$api.get('/dsr-tools/ffxiv/index.json');
      const res = response.data;
      // update time
      this.lastUpdate = new Date(res.lastUpdate);
      // data
      for (let area in res.huntingData) {
        let areaData = res.huntingData[area];
        this.data.push(areaData);
      }
      this.loading = false;
    },
    handleTabChange(val) {
      storage.setLS('dsr-tools_ffxiv-tab', val);
    },
  },
  async mounted() {
    await this.fetchData();
  },
};
</script>

<style lang="scss" scoped>
// hide empty header in mobile
::v-deep .v-data-table-header-mobile {
  display: none;
}

.table-title {
  display: block;
  padding: 1rem;
  margin-left: 2rem;
  font-size: 20px;
  font-weight: 600;
}

a {
  text-decoration: none;
  color: $color-info;
}

.text-trans {
  color: rgba(0, 0, 0, 0.5) !important;
}
</style>

// src/views/Game/FFXIV.jsx
import React, { useEffect, useState } from 'react';
import dayjs from 'dayjs';

import { Tabs, Table, Card, Alert, List } from 'antd';
import 'antd/lib/tabs/style/index.less';
import 'antd/lib/table/style/index.less';
import 'antd/lib/empty/style/index.less'; // table
import 'antd/lib/card/style/index.less';
import 'antd/lib/alert/style/index.less';
import 'antd/lib/list/style/index.less';

import './FFXIV.scss';
import Loading from '@/components/Loading';
import { api } from '@/utils/axios';

const shadowbringers = () => '5.X SHADOWBRINGERS';
const stormblood = () => '4.X STORMBLOOD';

/**
 * ffxiv page
 * @return {import('react').ReactElement}
 */
function FFXIV() {
  const [loading, setLoading] = useState(true);

  const [meta, setMeta] = useState({ lastUpdate: '', license: '' });
  const metaList = [
    {
      title: '数据更新',
      desc: '数据更新后 CDN 缓存需要约 10-15 分钟全球刷新, 若出现问题则最高需要 12 小时',
    },
    {
      title: '错误反馈',
      desc: '请使用右下角按钮直接进行客服提问反馈, 或至 NGA 原帖回帖反馈',
    },
    {
      title: '感谢访问',
      desc: '如果觉得本站对您有所帮助还请多多分享, 用户的使用是我更新的最大动力',
    },
    {
      title: 'NGA 原帖',
      desc: (
        <a href={meta.license} target='_blank'>
          {meta.license}
        </a>
      ),
    },
  ];

  const [chocobo, setChocobo] = useState({ shadowbringers: [], stormblood: [] });
  const [moogle, setMoogle] = useState({ shadowbringers: [], stormblood: [] });
  const [fatCat, setFatCat] = useState({ shadowbringers: [], stormblood: [] });
  useEffect(() => {
    (async () => {
      const res = await api.get('/dsr-tools/ffxiv/index.json');
      if (res.data) {
        setMeta({ lastUpdate: res.data.lastUpdate, license: res.data.license });
        setChocobo(res.data.huntingData.chocobo);
        setMoogle(res.data.huntingData.moogle);
        setFatCat(res.data.huntingData.fatCat);
        setTimeout(() => setLoading(false), 500);
      }
    })();
  }, []);

  const columns = [
    { title: '服务器', dataIndex: 'server', key: '服务器', align: 'center' },
    { title: '早车', dataIndex: ['timeTable', '0'], key: '早车', align: 'center' },
    { title: '午车', dataIndex: ['timeTable', '1'], key: '午车', align: 'center' },
    { title: '晚车', dataIndex: ['timeTable', '2'], key: '晚车', align: 'center' },
    { title: '灵车', dataIndex: ['timeTable', '3'], key: '灵车', align: 'center' },
    { title: '始发地', dataIndex: 'origin', key: '始发地', align: 'center' },
    { title: '路线', dataIndex: 'route', key: '路线', align: 'center' },
  ];
  const tableProps = {
    size: 'small',
    columns,
    pagination: false,
    scroll: { x: 'max-content' },
    rowKey: (record) => record.server,
  };
  const tabPanes = [
    { name: '陆行鸟', records: chocobo },
    { name: '莫古力', records: moogle },
    { name: '猫小胖', records: fatCat },
  ];

  return (
    <Loading loading={loading}>
      <div className='ffxiv'>
        <Tabs type='card' size='large' centered={true}>
          <Tabs.TabPane tab='关于' key='about' className='tabs-about'>
            <Alert
              message={`最后更新于 ${dayjs(meta.lastUpdate).format('YYYY-MM-DD HH:mm:ss')}`}
              type='success'
              showIcon={true}
            />
            <Card>
              <List
                dataSource={metaList}
                renderItem={(item) => (
                  <List.Item>
                    <List.Item.Meta title={item.title} description={item.desc} />
                  </List.Item>
                )}
              ></List>
            </Card>
          </Tabs.TabPane>
          {tabPanes.map((dataCenter) => (
            <Tabs.TabPane tab={dataCenter.name} key={dataCenter.name}>
              <Table
                {...tableProps}
                dataSource={dataCenter.records.shadowbringers}
                title={shadowbringers}
              />
              <Table
                {...tableProps}
                dataSource={dataCenter.records.stormblood}
                title={stormblood}
              />
            </Tabs.TabPane>
          ))}
        </Tabs>
      </div>
    </Loading>
  );
}

export default FFXIV;
