// pages/ffxiv.tsx
import { GetStaticProps } from 'next';
import { Fragment } from 'react';
import ffxiv, { XIVData, XIVPatchItem } from '../lib/ffxiv';

/**
 * 每天重新生成页面刷新数据
 */
export const getStaticProps: GetStaticProps = async () => {
  const data = await ffxiv(true);
  return { props: { data }, revalidate: 86400 };
};

import styles from './ffxiv.module.scss';
import { useState, useEffect, useCallback, useMemo } from 'react';
import dayjs, { isDST, tzdb } from '../utils/dayjs';
import ZButton from '../components/ZButton';
import ZCover from '../components/ZCover';
import ZList from '../components/ZList';
import ZSelect from '../components/ZSelect';
import { getLS, setLS } from '../utils/storage';

const infoList = [
  {
    title: '关于本站',
    content: '自 2020 年 2 月运营至今，国服最早的全区服狩猎时间汇总站',
  },
  {
    title: '数据更新',
    content:
      '数据更新后 CDN 缓存需要约 10-15 分钟全球刷新，若出现问题则最高需要 12 小时',
  },
  {
    title: '错误反馈',
    content: '请使用右下角按钮直接进行客服提问反馈，或至 NGA 原帖回帖反馈',
  },
  {
    title: 'NGA 原帖',
    content: (
      <a
        href='https://nga.178.com/read.php?tid=20339590'
        target='_blank'
        rel='noreferrer'
      >
        https://nga.178.com/read.php?tid=20339590
      </a>
    ),
  },
];

/**
 * 转换北京时间到目标时区
 * @param time 北京时间的 HH:mm
 * @param tz 目标时区
 */
function cstToTimeZone(time: string, tz: string) {
  // 获取当前北京时间的日期
  const cstDay = dayjs().tz('Asia/Shanghai').format('YYYY-MM-DD');
  // 合并北京时间的日期和时间
  const fullCSTTime = `${cstDay} ${time}`;
  // 转换为目标时区的时间
  return dayjs.tz(fullCSTTime, 'Asia/Shanghai').tz(tz);
}

interface TimeGridProps {
  times: string[];
  tz: string;
}

// 时间根据 24 小时制对应的百分比显示到对应位置
function TimeGrid({ times, tz }: TimeGridProps) {
  return (
    <div className={styles.timeGrid}>
      {times.map((time) => {
        const zonedTime = cstToTimeZone(time, tz);
        const zonedTimeString = zonedTime.format('HH:mm');
        return (
          <span key={time} className={styles.timeGridItem}>
            {zonedTimeString}
          </span>
        );
      })}
    </div>
  );
}

type DataCenter = 'chocobo' | 'moogle' | 'cat' | 'dog';

const validTabQuerys: Array<{ query: DataCenter; name: string }> = [
  { query: 'chocobo', name: '陆行鸟' },
  { query: 'moogle', name: '莫古力' },
  { query: 'cat', name: '猫小胖' },
  { query: 'dog', name: '豆豆柴' },
];

// 通过 Tab 名搜索数据的缓存
const dataSearchCache = new Map<DataCenter, XIVPatchItem[]>();

interface FFXIVProps {
  data: XIVData;
}

function FFXIV({ data }: FFXIVProps) {
  // 当前实际显示的 TabQuery
  const [curTab, setCurTab] = useState<DataCenter>('chocobo');
  const handleSwitchTab = useCallback((tab: DataCenter) => {
    setCurTab(tab);
    setLS('ffxiv-tab', tab);
  }, []);

  // 确保当前 Tab 更新
  useEffect(() => {
    const savedTab = getLS('ffxiv-tab');
    if (
      typeof savedTab === 'string' &&
      validTabQuerys.findIndex((v) => v.query === savedTab) >= 0
    ) {
      setCurTab(savedTab as DataCenter);
    }
  }, []);

  // 时区设置
  const [curTZ, setCurTZ] = useState('Asia/Shanghai');
  const handleTimeZoneChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => {
      const newTZ = e.target.value;
      setLS('ffxiv-tz', newTZ);
      setCurTZ(newTZ);
    },
    []
  );

  // 确保时区更新
  useEffect(() => {
    const savedTZ = getLS('ffxiv-tz');
    const guessTz = dayjs.tz.guess();
    if (typeof savedTZ === 'string' && tzdb.includes(savedTZ)) {
      setCurTZ(savedTZ);
    } else if (tzdb.includes(guessTz)) {
      setCurTZ(guessTz);
    }
  }, []);

  // 数据处理
  const dcPatches = useMemo(() => {
    // 寻找缓存
    const cached = dataSearchCache.get(curTab);
    if (cached) {
      return cached;
    }
    // 没有缓存查找数据
    const curDCName =
      validTabQuerys.find((v) => v.query === curTab)?.name || '';
    const curDCData = data?.dcs.find((v) => v.name === curDCName);
    const res = curDCData?.patches || [];
    dataSearchCache.set(curTab, res);
    return res;
  }, [curTab, data]);

  // 更新时间转换
  const updateMessage = useMemo(() => {
    const updateTime = dayjs(data?.stime || 0).tz(curTZ);
    let text = `更新于 ${updateTime.format('YYYY-MM-DD HH:mm')}`;
    if (isDST(updateTime)) {
      text += ' (DST)';
    }
    return text;
  }, [curTZ, data]);

  if (!data) {
    return (
      <div className={styles.container}>
        <ZCover type='error' />
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <div className={styles.control}>
        <div className={styles.tabs}>
          {validTabQuerys.map((tabQuery) => {
            return (
              <ZButton
                type={tabQuery.query === curTab ? 'primary' : 'transparent'}
                key={tabQuery.query}
                onClick={() => handleSwitchTab(tabQuery.query)}
              >
                {tabQuery.name}
              </ZButton>
            );
          })}
        </div>
        <div className={styles.update}>{updateMessage}</div>
        <div className={styles.selectGrid}>
          <span className={styles.tszspan}>时区</span>
          <ZSelect
            className={styles.tzselect}
            options={tzdb}
            value={curTZ}
            onChange={handleTimeZoneChange}
          />
        </div>
      </div>
      <div className={styles.content}>
        {!dcPatches.length && <div className={styles.empty}>暂无数据</div>}
        <table className={styles.table}>
          {dcPatches.map((patch) => {
            return (
              <Fragment key={patch.name}>
                <thead>
                  <tr>
                    <th className={styles.patch} colSpan={5}>
                      {patch.name}
                    </th>
                  </tr>
                  <tr>
                    <th>服务器</th>
                    <th className={styles.times}>时间表</th>
                    <th>始发地</th>
                    <th>路线</th>
                    <th>备注</th>
                  </tr>
                </thead>
                <tbody>
                  {patch?.servers.map((server) => {
                    return (
                      <tr key={server.name}>
                        <td>{server.name}</td>
                        <td className={styles.times}>
                          <TimeGrid times={server.times} tz={curTZ} />
                        </td>
                        <td>{server.start}</td>
                        <td>{server.route}</td>
                        <td>{server.comment}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </Fragment>
            );
          })}
        </table>
      </div>
      <ZList className={styles.notice} list={infoList} />
    </div>
  );
}

export default FFXIV;

// src/views/FFXIV/FFXIV.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { ISpinnerThird, ICheckCircle } from '../../icons';
import dayjs, { tzdb, isDST } from '../../utils/dayjs';
import { getLS, setLS } from '../../utils/storage';
import useSWR from '../../hooks/useSWR';
import ZButton from '../../components/ZButton.vue';
import ZSelect from '../../components/ZSelect.vue';
import ZList from '../../components/ZList.vue';
import ZExtLink from '../../components/ZExtLink.vue';
import ZLoading from '../../components/ZLoading.vue';
import TimeGrid from './TimeGrid.vue';

interface XIVServerItem {
  name: string;
  times?: string[];
  start?: string;
  route?: string;
  comment?: string;
}
interface XIVPatchItem {
  name: string;
  servers: XIVServerItem[];
}
interface XIVDCItem {
  name: string;
  patches: XIVPatchItem[];
}
interface XIVData {
  time: number;
  data: XIVDCItem[];
}

// 拉取数据
const { stale, data } = useSWR<XIVData | null>(
  'https://cdn.dsrkafuu.net/json/ffxiv.min.json'
);

const infoList = [
  {
    title: '关于本站',
    content: '自 2020 年 2 月运营至今，国服最早的全区服狩猎时间汇总站',
  },
  {
    title: '数据更新',
    content:
      '数据更新后 CDN 缓存需要约 10-15 分钟全球刷新，若出现问题则最高需要 12 小时',
  },
  {
    title: 'NGA 原帖',
    content: 'https://nga.178.com/read.php?tid=20339590',
  },
  {
    title: '联系方式',
    content: '请至 NGA 原帖回复或联系 QQ 2366715664',
  },
];

// tab 设置
type DataCenter = 'chocobo' | 'moogle' | 'cat' | 'dog';
// 当前实际显示的 tab
const validTabs: Array<{ query: DataCenter; name: string }> = [
  { query: 'chocobo', name: '陆行鸟' },
  { query: 'moogle', name: '莫古力' },
  { query: 'cat', name: '猫小胖' },
  { query: 'dog', name: '豆豆柴' },
];
let initialTab: DataCenter = 'chocobo';
const savedTab = getLS('ffxiv:tab');
if (savedTab && validTabs.find((v) => v.query === savedTab)) {
  initialTab = savedTab as DataCenter;
}
const curTab = ref(initialTab);
const handleSwitchTab = (tab: DataCenter) => {
  curTab.value = tab;
  setLS('ffxiv:tab', tab);
};

// 时区设置
let initialTZ = 'Asia/Shanghai';
const savedTZ = getLS<string>('ffxiv:tz');
const guessTz = dayjs.tz.guess();
if (savedTZ && tzdb.includes(savedTZ)) {
  initialTZ = savedTZ;
} else if (tzdb.includes(guessTz)) {
  initialTZ = guessTz;
}
const curTZ = ref(initialTZ);
watch(curTZ, (newTZ) => {
  curTZ.value = newTZ;
  setLS('ffxiv:tz', newTZ);
});

// 更新时间
const updateMessage = computed(() => {
  const updateTime = dayjs(data.value?.time || 0).tz(curTZ.value);
  let text = `生成于 ${updateTime.format('YYYY-MM-DD HH:mm')}`;
  if (isDST(updateTime)) {
    text += ' (DST)';
  }
  return text;
});

// 数据处理
const dcPatches = computed(() => {
  const curDCName = validTabs.find((v) => v.query === curTab.value)?.name || '';
  const curDCData = data.value?.data?.find((v) => v.name === curDCName);
  const res = curDCData?.patches || null;
  return res;
});
</script>

<template>
  <div class="ffxiv">
    <div class="control">
      <div class="tabs">
        <ZButton
          v-for="tab of validTabs"
          :type="tab.query === curTab ? 'primary' : undefined"
          :key="tab.query"
          @click="handleSwitchTab(tab.query)"
        >
          {{ tab.name }}
        </ZButton>
      </div>
      <div class="update">{{ updateMessage }}</div>
      <div class="tz">
        <ZSelect
          class="tz__inner"
          name="timezone"
          v-model="curTZ"
          :options="tzdb"
        />
        <div :class="['status', { 'status--success': !stale }]">
          <ISpinnerThird v-if="stale" />
          <ICheckCircle v-else />
        </div>
      </div>
    </div>
    <ZLoading v-if="!dcPatches || !dcPatches.length" />
    <template v-else>
      <div class="content" v-for="patch of dcPatches" :key="patch.name">
        <table class="table">
          <thead>
            <tr>
              <th class="patch" colspan="5">{{ patch.name }}</th>
            </tr>
            <tr>
              <th>服务器</th>
              <th class="times">时间表</th>
              <th>始发地</th>
              <th>路线</th>
              <th>备注</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="server of patch.servers" :key="server.name">
              <td>{{ server.name }}</td>
              <td class="times">
                <TimeGrid :times="server.times || []" :tz="curTZ" />
              </td>
              <td>{{ server.start }}</td>
              <td>{{ server.route }}</td>
              <td>{{ server.comment }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </template>
    <div class="notice">
      <ZList :list="infoList" v-slot="{ item }">
        <template v-if="(item.content as string)?.startsWith('http')">
          <ZExtLink type="primary" :href="(item.content as string)">
            {{ item.content }}
          </ZExtLink>
        </template>
        <template v-else>
          {{ item.content }}
        </template>
      </ZList>
    </div>
  </div>
</template>

<style scoped src="./FFXIV.scss"></style>
