// src/components/ZList.vue
<script setup lang="ts">
/**
 * @fileoverview
 * 可以通过插槽自定义的列表，默认显示 content 属性
 */

interface ZListItem {
  title?: string;
  [key: string]: unknown;
}
interface ZListProps {
  list: ZListItem[];
  inline?: boolean;
}
defineProps<ZListProps>();
</script>

<template>
  <div :class="['z-list', { 'z-list--inline': inline }]">
    <div
      class="z-list__section"
      v-for="(item, idx) of list"
      :key="item.title || idx"
    >
      <span class="z-list__title" v-if="item.title">{{ item.title }}</span>
      <div class="z-list__content">
        <slot :item="item">
          {{ item.content || JSON.stringify(item) }}
        </slot>
      </div>
    </div>
  </div>
</template>

<style lang="scss" src="./ZList.scss"></style>

// components/ZList.tsx
import styles from './ZList.module.scss';
import clsx from 'clsx';

interface ZListItem {
  title?: string;
  content: React.ReactNode;
}

interface ZListProps {
  list: ZListItem[];
  inline?: boolean;
  className?: string;
}

function ZList({ list, inline, className }: ZListProps) {
  return (
    <div className={clsx(styles.zlist, { [styles.inline]: inline }, className)}>
      {list.map((item, idx) => {
        let titleRender: React.ReactNode = item.title;
        if (!titleRender) {
          titleRender = null;
        } else {
          titleRender = <span className={styles.title}>{titleRender}</span>;
        }

        let contentRender: React.ReactNode = item.content;
        if (!contentRender) {
          contentRender = null;
        } else if (typeof contentRender === 'string') {
          const paras = contentRender.split('\n');
          contentRender = paras.map((para, idx) => <p key={idx}>{para}</p>);
        } else {
          contentRender = <p>{contentRender}</p>;
        }

        return (
          <div
            className={clsx(styles.section, 'markdown')}
            key={item.title || idx.toString()}
          >
            {titleRender}
            {contentRender}
          </div>
        );
      })}
    </div>
  );
}

export default ZList;
