// components/ZButton.tsx
import styles from './ZButton.module.scss';
import clsx from 'clsx';
import { useCallback } from 'react';

interface ZButtonProps {
  type?: 'primary' | 'transparent' | 'success' | 'danger';
  href?: string;
  icon?: React.ReactNode;
  disabled?: boolean;
  children?: React.ReactNode;
  className?: string;
  onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
  suppressHydrationWarning?: boolean;
}

function ZButton({
  children,
  type = 'transparent',
  href,
  icon,
  disabled,
  className,
  onClick,
  suppressHydrationWarning,
}: ZButtonProps) {
  const ButtonTag = href ? 'a' : 'button';

  // 若添加了链接，则点击事件无效
  const handleClick = useCallback(
    (e: React.MouseEvent<HTMLButtonElement | HTMLAnchorElement>) => {
      return onClick && onClick(e as React.MouseEvent<HTMLButtonElement>);
    },
    [onClick]
  );

  const buttonProps = {
    disabled: !href && disabled,
    onClick: href ? undefined : handleClick,
    href,
    target: '_blank',
    rel: 'noopener',
  };

  return (
    <ButtonTag
      className={clsx(
        styles.btn,
        {
          [styles.primaryColor]: type === 'primary',
          [styles.transparentColor]: type === 'transparent',
          [styles.successColor]: type === 'success',
          [styles.dangerColor]: type === 'danger',
          [styles.disabled]: disabled,
          [styles.withIcon]: children && icon,
          [styles.onlyIcon]: !children && icon,
        },
        className
      )}
      {...buttonProps}
      suppressHydrationWarning={suppressHydrationWarning}
    >
      {icon}
      {children}
    </ButtonTag>
  );
}

export default ZButton;

// src/components/ZButton.vue
<script setup lang="ts">
import { computed } from 'vue';

interface ZButtonProps {
  type?: 'primary' | 'success' | 'danger';
  href?: string;
  disabled?: boolean;
}
const props = defineProps<ZButtonProps>();

const tagName = computed(() => (props.href ? 'a' : 'button'));

const emit = defineEmits<{
  (event: 'click', e: MouseEvent): void;
}>();
const handleClick = (e: MouseEvent) => {
  if (props.disabled) return;
  emit('click', e);
};
</script>

<template>
  <component
    :is="tagName"
    :class="[
      'z-button',
      {
        'z-button__primary': type === 'primary',
        'z-button__success': type === 'success',
        'z-button__danger': type === 'danger',
        'z-button__with-icon': $slots.default && $slots.icon,
        'z-button__only-icon': !$slots.default && $slots.icon,
        'z-button--disabled': disabled,
      },
    ]"
    @click="handleClick"
    :disabled="(!href && disabled) || undefined"
    :href="href || undefined"
    :target="href ? '_blank' : undefined"
    :rel="href ? 'noopener' : undefined"
  >
    <slot name="icon" />
    <slot />
  </component>
</template>

<style lang="scss" src="./ZButton.scss"></style>
