// components/ZSelect.tsx
import styles from './ZSelect.module.scss';
import clsx from 'clsx';

interface ZSelectProps {
  value: string;
  options: string[];
  className?: string;
  onChange?: (e: React.ChangeEvent<HTMLSelectElement>) => void;
}

function ZSelect({ value, options, className, onChange }: ZSelectProps) {
  return (
    <div className={clsx(styles.select, className)}>
      <select className={styles.selectInner} value={value} onChange={onChange}>
        {options.map((option) => (
          <option className={styles.option} key={option} value={option}>
            {option}
          </option>
        ))}
      </select>
    </div>
  );
}

export default ZSelect;

// src/components/ZSelect.vue
<script setup lang="ts">
interface ZSelectProps {
  name: string;
  options: string[];
  modelValue: string;
}
defineProps<ZSelectProps>();

const emit = defineEmits<{
  (event: 'update:modelValue', value: string): void;
}>();
const handleChange = (e: Event) => {
  const target = e.target as HTMLSelectElement;
  emit('update:modelValue', target?.value || '');
};
</script>

<template>
  <div class="z-select">
    <select
      class="z-select__inner"
      :value="modelValue"
      @change="handleChange"
      :name="name"
    >
      <option v-for="item of options" :key="item" :value="item">
        {{ item }}
      </option>
    </select>
  </div>
</template>

<style lang="scss" src="./ZSelect.scss"></style>
