// components/ZTextArea.tsx
import styles from './ZTextArea.module.scss';
import clsx from 'clsx';

interface ZTextAreaProps {
  value: string;
  className?: string;
  onChange?: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
}

function ZTextArea({ value, className, onChange }: ZTextAreaProps) {
  return (
    <textarea
      className={clsx(styles.textarea, className)}
      value={value}
      onChange={onChange}
    ></textarea>
  );
}

export default ZTextArea;

// src/components/ZTextArea.vue
<script setup lang="ts">
interface ZTextAreaProps {
  modelValue: string;
}
defineProps<ZTextAreaProps>();

const emit = defineEmits<{
  (event: 'update:modelValue', value: string): void;
}>();
const handleInput = (e: Event) => {
  const target = e.target as HTMLTextAreaElement;
  emit('update:modelValue', target?.value || '');
};
</script>

<template>
  <textarea
    class="textarea"
    :value="modelValue"
    @input="handleInput"
  ></textarea>
</template>

<style lang="scss" src="./ZTextArea.scss"></style>
