// src/views/KataCode/KataCode.vue
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue';
import { throttle } from 'dsr-design/utils';
import { IChevronRight, IChevronLeft, ITrash } from '../../icons';
import { decodeKata, encodeKata } from '../../utils/katacode';
import { log } from '../../utils/logger';
import { ZButton, ZMessage, ZList, ZTextArea } from '../../components';
import { isPC } from '../../utils/env';

const info = [
  {
    title: '密文格式',
    content: '请注意相同的明文可能会产生不同的密文',
  },
  {
    title: '数据支持',
    content: '支持任意 Unicode 字符',
  },
  {
    title: '免责声明',
    content: '本站不对使用此工具造成的任何结果负相关法律责任',
  },
];

const srcStr = ref('');
const encStr = ref('');

const handleClear = () => {
  srcStr.value = '';
  encStr.value = '';
  ZMessage.info('已清空内容');
};
const handleEncode = async () => {
  try {
    const res = await encodeKata(srcStr.value);
    if (res) {
      encStr.value =
        res +
        `\n${new Array(40).fill('-').join('')}\n` +
        window.location.origin +
        window.location.pathname;
      log('katacode encoded');
      ZMessage.success('已生成密文');
    }
  } catch {
    ZMessage.error('生成密文失败 请检查输入字符');
  }
};
const handleDecode = async () => {
  try {
    const res = await decodeKata(encStr.value);
    if (res) {
      srcStr.value = res;
      log('katacode decoded');
      ZMessage.success('解密成功');
    }
  } catch {
    ZMessage.error('解密失败 请检查输入字符');
  }
};

// PC 展示宽信息
const inline = ref(isPC());
// 响应缩放
const handleResize = throttle(() => {
  inline.value = isPC();
});
window.addEventListener('resize', handleResize);
onBeforeUnmount(() => {
  window.removeEventListener('resize', handleResize);
});
</script>

<template>
  <div class="katacode">
    <div class="main">
      <div class="card card--input">
        <ZTextArea class="input" v-model="srcStr" />
      </div>
      <div class="control">
        <ZButton class="control__btn" type="primary" @click="handleEncode">
          <template #icon><IChevronRight /></template>
          加密
        </ZButton>
        <ZButton class="control__btn" type="primary" @click="handleDecode">
          <template #icon><IChevronLeft /></template>
          解密
        </ZButton>
        <ZButton class="control__btn" type="danger" @click="handleClear">
          <template #icon><ITrash /></template>
          清空
        </ZButton>
      </div>
      <div class="card card--input">
        <ZTextArea class="input" v-model="encStr" />
      </div>
    </div>
    <div class="notice">
      <div class="card">
        <ZList :list="info" :inline="inline" />
      </div>
    </div>
  </div>
</template>

<style scoped src="./KataCode.scss"></style>

// pages/katacode.tsx
import styles from './katacode.module.scss';
import { useCallback, useState } from 'react';
import { message } from '../components/ZMessage';
import ZButton from '../components/ZButton';
import ZTextArea from '../components/ZTextArea';
import ZList from '../components/ZList';
import { encodeKata, decodeKata } from '../utils/katacode';
import { ChevronLeft, ChevronRight, Trash } from '../icons';

const infoList = [
  {
    title: '密文格式',
    content: (
      <>
        请注意相同的明文可能会产生不同的密文，例如密文 <code>ィゾヮイダ</code>和{' '}
        <code>ィゾヲイダ</code> 均对应明文 <code>12</code>
      </>
    ),
  },
  {
    title: '数据支持',
    content: '支持任意格式 Unicode 字符，例如 emoji 表情等',
  },
  {
    title: '免责声明',
    content: '本站点作者 DSRKafuU 不对使用此工具造成的任何结果负相关法律责任',
  },
];

function KataCode() {
  const [srcValue, setSrcValue] = useState('');
  const [encValue, setEncValue] = useState('');

  const clearValue = useCallback(() => {
    setSrcValue('');
    setEncValue('');
    message.info('已清空内容');
  }, []);
  const encodeValue = useCallback(async (val = '') => {
    try {
      const res = await encodeKata(val);
      setEncValue(res);
      message.success('加密成功');
    } catch {
      message.error('加密失败 请检查输入字符');
    }
  }, []);
  const decodeValue = useCallback(async (val = '') => {
    try {
      val = val.trim();
      const res = await decodeKata(val);
      setSrcValue(res);
      message.success('解密成功');
    } catch {
      message.error('解密失败 请检查输入字符');
    }
  }, []);

  return (
    <div className={styles.container}>
      <div className={styles.main}>
        <div className={styles.card}>
          <ZTextArea
            className={styles.input}
            value={srcValue}
            onChange={(e) => setSrcValue(e.target.value)}
          />
        </div>
        <div className={styles.control}>
          <ZButton
            className={styles.btn}
            type='primary'
            onClick={() => encodeValue(srcValue)}
            icon={<ChevronRight />}
          >
            加密
          </ZButton>
          <ZButton
            className={styles.btn}
            type='primary'
            onClick={() => decodeValue(encValue)}
            icon={<ChevronLeft />}
          >
            解密
          </ZButton>
          <ZButton
            className={styles.btn}
            type='danger'
            onClick={clearValue}
            icon={<Trash />}
          >
            清空
          </ZButton>
        </div>
        <div className={styles.card}>
          <ZTextArea
            className={styles.input}
            value={encValue}
            onChange={(e) => setEncValue(e.target.value)}
          />
        </div>
      </div>
      <ZList className={styles.notice} list={infoList} />
    </div>
  );
}

export default KataCode;
