// pages/bangumi.tsx
import { GetStaticProps } from 'next';
import bangumi from '../lib/bangumi';

interface BangumiAPIDataItem {
  id: number;
  url: string;
  rawName: string;
  transName?: string;
  image?: string;
  rating?: number;
  hot?: number;
}

interface BangumiAPIDataDay {
  weekday: string;
  items: BangumiAPIDataItem[];
}

type BangumiAPIData = BangumiAPIDataDay[];

/**
 * 需要手动触发重新构建
 */
export const getStaticProps: GetStaticProps = async () => {
  const data = await bangumi();
  // 解析数据
  let parsedData: BangumiAPIData | null = null;
  if (data && Array.isArray(data)) {
    parsedData = data.map((weekday) => {
      const parsed: BangumiAPIDataDay = {
        weekday: `${weekday.weekday.cn}`.replace('星期', '周'),
        items: [],
      };
      weekday.items.forEach((item) => {
        const ret: BangumiAPIDataItem = {
          id: item.id,
          url: `${item.url}`.replace(/https?:\/\//gi, '//'), // 确保链接不带协议
          rawName: item.name,
        };
        // 翻译名
        if (item.name_cn) {
          ret.transName = item.name_cn;
        }
        // 图片
        if (item.images && item.images.large) {
          ret.image = `${item.images.large}`.replace(/https?:\/\//gi, '//');
        }
        // 评分和热度
        if (item.rating?.score) {
          ret.rating = item.rating.score;
        }
        if (item.collection?.doing) {
          ret.hot = item.collection.doing;
        }
        parsed.items.push(ret);
      });
      return parsed;
    });
  }
  return {
    props: { data: parsedData },
  };
};

import styles from './bangumi.module.scss';
import Image from 'next/image';
import { useCallback, useMemo, useState } from 'react';
import ZButton from '../components/ZButton';
import ZCover from '../components/ZCover';
import ZRadio from '../components/ZRadio';
import { Rating } from 'react-simple-star-rating';
import { FireAlt, Star } from '../icons';

/**
 * 格式化热度数据
 */
function formatHot(hot = 0) {
  return `${hot}`;
}

interface BangumiDayProps {
  data: BangumiAPIDataDay | null;
}

function BangumiDay({ data }: BangumiDayProps) {
  if (!data) {
    return <div className={styles.day}></div>;
  }
  return (
    <div className={styles.day}>
      <div className={styles.daycard}>
        <div className={styles.daytitle}>{data.weekday}</div>
        <div className={styles.daylist}>
          {data.items.map((item) => {
            return (
              <a
                key={item.id}
                className={styles.dayitem}
                href={item.url}
                target='_blank'
                rel='noopener'
              >
                <div className={styles.dayimage}>
                  {item.image ? (
                    <Image
                      src={`https:${item.image}`}
                      width={80}
                      height={80}
                      objectFit='cover'
                    />
                  ) : null}
                </div>
                <div className={styles.daymeta}>
                  <h3 className={styles.dayname}>{item.rawName}</h3>
                  {item.transName && (
                    <span className={styles.daytrans}>{item.transName}</span>
                  )}
                  <div className={styles.dayscore}>
                    <div className={styles.rating}>
                      <Rating
                        className={styles.rtpn}
                        ratingValue={(item.rating || 0) * 10}
                        readonly={true}
                        allowHalfIcon={true}
                        allowHover={false}
                        fillColor='#8aa2d3'
                        fullIcon={<Star />}
                        emptyIcon={<Star />}
                      />
                      {typeof item.rating === 'number' && item.rating
                        ? item.rating.toFixed(1)
                        : '-.-'}
                    </div>
                    <div className={styles.hot}>
                      {formatHot(item.hot)}
                      <FireAlt />
                    </div>
                  </div>
                </div>
              </a>
            );
          })}
        </div>
      </div>
    </div>
  );
}

interface BangumiProps {
  data: BangumiAPIData | null;
}

function Bangumi({ data }: BangumiProps) {
  const [curWeekdayIdx, setCurWeekdayIdx] = useState(3);
  const [sortRule, setSortRule] = useState(0);

  const sorter = useCallback(
    (a: BangumiAPIDataItem, b: BangumiAPIDataItem) => {
      if (sortRule === 0) {
        return (b.hot || 0) - (a.hot || 0);
      } else {
        return (b.rating || 0) - (a.rating || 0);
      }
    },
    [sortRule]
  );

  const todayData = useMemo(() => {
    const _data = data?.[curWeekdayIdx];
    if (!_data) {
      return null;
    }
    return {
      weekday: _data.weekday,
      items: _data.items.sort(sorter),
    };
  }, [curWeekdayIdx, data, sorter]);
  const prevdayData = useMemo(() => {
    const idx = curWeekdayIdx - 1;
    if (idx > 7 || idx < 0) {
      return null;
    }
    const _data = data?.[idx];
    if (!_data) {
      return null;
    }
    return {
      weekday: _data.weekday,
      items: _data.items.sort(sorter),
    };
  }, [curWeekdayIdx, data, sorter]);
  const nextdayData = useMemo(() => {
    const idx = curWeekdayIdx + 1;
    if (idx > 7 || idx < 0) {
      return null;
    }
    const _data = data?.[idx];
    if (!_data) {
      return null;
    }
    return {
      weekday: _data.weekday,
      items: _data.items.sort(sorter),
    };
  }, [curWeekdayIdx, data, sorter]);

  if (!data) {
    return (
      <div className={styles.container}>
        <ZCover type='error' />
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <div className={styles.control}>
        <div className={styles.weekday}>
          {data.map((weekday, idx) => (
            <ZButton
              type={idx === curWeekdayIdx ? 'primary' : 'transparent'}
              key={idx}
              onClick={() => setCurWeekdayIdx(idx)}
            >
              {weekday.weekday}
            </ZButton>
          ))}
        </div>
        <div className={styles.sorter}>
          <ZRadio value={sortRule === 0} onChange={() => setSortRule(0)}>
            热度排序
          </ZRadio>
          <ZRadio value={sortRule === 1} onChange={() => setSortRule(1)}>
            评分排序
          </ZRadio>
        </div>
      </div>
      <div className={styles.content}>
        <BangumiDay data={prevdayData} />
        <BangumiDay data={todayData} />
        <BangumiDay data={nextdayData} />
      </div>
    </div>
  );
}

export default Bangumi;

// src/views/Bangumi/Bangumi.vue
<script setup lang="ts">
import type { BangumiAPIData } from '.';
import { computed, ref, toRaw } from 'vue';
import { cloneDeep } from 'dsr-design/utils';
import useSWR from '../../hooks/useSWR';
import ZButton from '../../components/ZButton.vue';
import ZRadio from '../../components/ZRadio.vue';
import BangumiDay from './BangumiDay.vue';

const { stale, data } = useSWR<BangumiAPIData>(
  'https://cdn.dsrkafuu.net/json/bangumi.min.json'
);

const curWeekdayIdx = ref(3);
const setCurWeekdayIdx = (idx: number) => {
  curWeekdayIdx.value = idx;
};
const sortRule = ref(0);
const setSortRule = (rule: number) => {
  sortRule.value = rule;
};

const sortedData = computed(() => {
  const rawData = toRaw(data.value) || [];
  const rule = sortRule.value;
  const copiedData = cloneDeep(rawData);
  copiedData.forEach((day) => {
    day.items.sort((a, b) => {
      if (rule === 0) {
        return (b.hot || 0) - (a.hot || 0);
      } else {
        return (b.rating || 0) - (a.rating || 0);
      }
    });
  });
  return copiedData;
});

const todayData = computed(() => {
  const _data = sortedData.value[curWeekdayIdx.value];
  if (!_data) {
    return null;
  }
  return _data;
});
const prevdayData = computed(() => {
  const idx = curWeekdayIdx.value - 1;
  if (idx > 7 || idx < 0) {
    return null;
  }
  const _data = sortedData.value[idx];
  if (!_data) {
    return null;
  }
  return _data;
});
const nextdayData = computed(() => {
  const idx = curWeekdayIdx.value + 1;
  if (idx > 7 || idx < 0) {
    return null;
  }
  const _data = sortedData.value[idx];
  if (!_data) {
    return null;
  }
  return _data;
});
</script>

<template>
  <div class="bangumi">
    <div class="control">
      <div class="weekday">
        <ZButton
          v-for="(weekday, idx) of data"
          :type="idx === curWeekdayIdx ? 'primary' : undefined"
          :key="idx"
          @click="setCurWeekdayIdx(idx)"
        >
          {{ weekday.weekday }}
        </ZButton>
      </div>
      <div class="sorter">
        <ZRadio :value="sortRule === 0" @click="setSortRule(0)">
          热度排序
        </ZRadio>
        <ZRadio :value="sortRule === 1" @click="setSortRule(1)">
          评分排序
        </ZRadio>
      </div>
    </div>
    <div class="content">
      <BangumiDay :data="prevdayData" />
      <BangumiDay :data="todayData" />
      <BangumiDay :data="nextdayData" />
    </div>
  </div>
</template>

<style scoped src="./Bangumi.scss"></style>
